name: sdk
on: 
  workflow_dispatch:
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Delete Files
      run: |
        docker rmi `docker images -q`
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
        sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* adoptopenjdk* mysql* php* mongodb* dotnet* moby* snapd* || true
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Show system
      run: |
        lscpu
        free -h
        df -Th
        uname -a
    - name: Installation depends
      run: |
        sudo -E apt update -y
        sudo -E apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
        bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib \
        git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev \
        libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz \
        mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools \
        libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip \
        vim wget xmlto xxd zlib1g-dev python3-setuptools
    - name: Clone source code
      run: |
        wget https://downloads.openwrt.org/releases/23.05.0/targets/x86/64/openwrt-sdk-23.05.0-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz
        tar -J -x -f openwrt-sdk-*.tar.xz
        #wget https://downloads.immortalwrt.org/releases/23.05.0-rc4/targets/x86/64/immortalwrt-sdk-23.05.0-rc4-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz
        #wget https://downloads.immortalwrt.org/releases/21.02.7/targets/x86/64/immortalwrt-imagebuilder-21.02.7-x86-64.Linux-x86_64.tar.xz
        #tar -J -x -f immortalwrt-sdk-*.tar.xz
    - name: Clone luci-app-qbittorrent
      run: |
        cd openwrt-sdk-*/package
        git clone https://github.com/sbwml/luci-app-qbittorrent.git
        
    - name: config qbit
      run: |
        cd openwrrt-sdk-*/

        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make defconfig
        make package/luci-app-qbittorrent/luci-app-qbittorrent/compile   # 编译 qBittorrent4.5.5 应用程序
    - name: Upload immortalwrt firmware
      uses: actions/upload-artifact@master
      with:
        name: immortalwrt-sdk
        path: immortalwrt-sdk-23.05.0-rc4-x86-64_gcc-12.3.0_musl.Linux-x86_64/bin/packages
